backend:
  name: git-gateway
  branch: master # Branch to update (optional; defaults to master)
media_folder: 'assets/uploads'
collections:
  - name: 'blog'
    label: 'Noticias'
    folder: '_posts/'
    create: true
    slug: '{{year}}-{{month}}-{{day}}-{{title}}'
    editor:
      preview: false
    fields:
      - {label: 'Layout', name: 'layout', widget: 'hidden', default: 'post'}
      - {label: "Imagen thumbnail", name: image_thumbnail, widget: image}
      - {label: "Imagen hero", name: image_hero, widget: image}
      - {label: "Fecha", name: date, widget: date, format: 'Do MMM'}
      - {label: "Título", name: title, widget: string}
      - {label: "Contenido", name: content, widget: markdown}
      - label: "Categoría"
        name: "color"
        widget: "select"
        options:
          - { label: "Noticias", value: "dash-pink" }
          - { label: "Eventos", value: "dash-green" }
          - { label: "Prensa", value: "dash-purple" }
          - { label: "Global", value: "dash-orange" }
  - name: 'initiatives'
    label: 'Iniciativas'
    folder: '_initiatives/'
    create: true
    slug: '{{title}}'
    editor:
      preview: false
    fields:
      - {label: 'Layout', name: 'layout', widget: 'hidden', default: 'initiative'}
      - {label: "Activo", name: active, widget: boolean}
      - {label: "Imagen thumbnail", name: image_thumbnail, widget: image}
      - {label: "Imagen hero", name: image_hero, widget: image}
      - {label: "Título", name: title, widget: string}
      - {label: "Bajada", name: brief, widget: string}
      - {label: "Contenido", name: content_block, widget: markdown}
      - {label: "Sitio web", name: external_link, widget: string, required: false}
      - {label: "Alianza 1 - Org", name: alliance_1_org, widget: string, required: false}
      - {label: "Alianza 1 - Logo", name: alliance_1_logo, widget: image, required: false}
      - {label: "Alianza 2 - Org", name: alliance_2_org, widget: string, required: false}
      - {label: "Alianza 2 - Logo", name: alliance_2_logo, widget: image, required: false}
      - {label: "Alianza 3 - Org", name: alliance_3_org, widget: string, required: false}
      - {label: "Alianza 3 - Logo", name: alliance_3_logo, widget: image, required: false}
      - {label: "Alianza 4 - Org", name: alliance_4_org, widget: string, required: false}
      - {label: "Alianza 4 - Logo", name: alliance_4_logo, widget: image, required: false}
      - {label: "Alianza 5 - Org", name: alliance_5_org, widget: string, required: false}
      - {label: "Alianza 5 - Logo", name: alliance_5_logo, widget: image, required: false}
      - {label: "Alianza 6 - Org", name: alliance_6_org, widget: string, required: false}
      - {label: "Alianza 6 - Logo", name: alliance_6_logo, widget: image, required: false}
